[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT app:app --workers 1 --timeout 300 --preload"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PYTHON_VERSION = "3.10.12"
PIP_NO_CACHE_DIR = "1"
PYTHONUNBUFFERED = "1"